[package]
name = "ql_rcon"
version = "0.1.0"
authors = ["Markus 'ShiN0' Gaertner"]
edition = "2021"
rust-version = "1.85"

[profile.release]
strip = "symbols"
opt-level = "z"
lto = "fat"
codegen-units = 1

[dependencies]
zmq = { version = ">=0.10", default-features = false }
clap = { version = ">=4.5", default-features = false, features = ["std", "derive", "color", "help", "usage", "wrap_help", "string"] }
anyhow = { version = ">=1.0", default-features = false }
uuid = { version = ">=1.11", default-features = false, features = ["v4"] }
simple-home-dir = { version = ">=0.4", default-features = false }
linefeed = { version = ">=0.6", default-features = false }
termcolor = { version = ">=1.4", default-features = false }
crossbeam-channel = { version = ">=0.5", default-features = false, features = ["std"] }
regex = { version = ">=1.11", default-features = false, features = ["perf", "unicode"] }
