cargo-features = ["profile-rustflags"]

[package]
name = "ql_rcon"
version = "0.1.0"
authors = ["Markus 'ShiN0' Gaertner"]
edition = "2021"
rust-version = "1.83"

[profile.release]
strip = "symbols"
opt-level = "z"
lto = "fat"
codegen-units = 1

[profile.release.build-override]
rustflags = ["-Zlocation-detail=none"]

[dependencies]
derive_more = { version = ">=2.0", default-features = false, features = ["as_ref"] }
tap = { version = ">=1.0", default-features = false }
tokio = { version = ">=1.45", default-features = false, features = ["default", "macros", "rt", "rt-multi-thread", "sync"] }
futures = { version = ">=0.3.31", default-features = false, features = ["async-await"] }
zmq = { version = ">=0.10", default-features = false }
clap = { version = ">=4.5", default-features = false, features = ["std", "derive", "color", "help", "usage", "wrap_help", "string"] }
anyhow = { version = ">=1.0", default-features = false }
uuid = { version = ">=1.17", default-features = false, features = ["v4"] }
directories = { version = ">=6.0", default-features = false }
linefeed = { version = ">=0.6", default-features = false }
termcolor = { version = ">=1.4", default-features = false }
regex = { version = ">=1.11", default-features = false, features = ["perf", "unicode"] }
