[package]
name = "azmq"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
anyhow = { workspace = true, default-features = false }
derive_more = { workspace = true, default-features = false, features = ["as_ref"]}
zmq = { workspace = true, default-features = false }

[lints]
workspace = true
