on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - run: cargo check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy
      - run: cargo clippy -- -D warnings

  build-linux:
    name: build (Linux)
    runs-on: ubuntu-latest
    needs: [ check, clippy ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - run: cargo build --release --verbose
      - name: Provide build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ql_zmq_linux
          path: |
            target/release/ql_zmq_rcon
            target/release/ql_zmq_stats

  build-windows:
    name: build (Windows)
    runs-on: windows-latest
    needs: [ check, clippy ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install toolchain
        with:
          toolchain: nightly
        uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release --verbose
      - name: Provide build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ql_zmq_windows
          path: |
            target/release/ql_zmq_rcon.exe
            target/release/ql_zmq_stats.exe

  build-macos:
    name: build (MacOS)
    runs-on: macos-latest
    needs: [ check, clippy ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - run: cargo build --release --verbose
      - name: Provide build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ql_zmq_macos
          path: |
            target/release/ql_zmq_rcon
            target/release/ql_zmq_stats
